apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
  namespace: kafka
spec:
  type: LoadBalancer
  selector:
    component: kafka-manager
  ports:
  - name: http
    port: 9000
    protocol: TCP